include "hardware.inc"

DEF ENABLE_AUDIO EQU $80
DEF AUDIO_TERM EQU $FF
DEF MIN_VOLUME EQU $0
DEF QUIET_VOLUME EQU $22
DEF MAX_VOLUME EQU $77

/*******************************************************
* AUDIO FUNCTIONS
* Simple multi-purpose audio functions
********************************************************/
SECTION "AudioHigherVars", HRAM

    hIsMusicReady:: db

SECTION "AudioVars", WRAM0

    wLastTrackPlayed:: dw

/*******************************************************
* VOLUME
********************************************************/
SECTION "VolumeFunctions", ROM0

; Turn off the volume
VolumeOff::
    xor a
    ld [rAUDENA], a

    ret

; Turn on and increase the volume
VolumeUp::
    ld a, ENABLE_AUDIO
    ld [rAUDENA], a
    ld a, AUDIO_TERM
    ld [rAUDTERM], a

    ld a, MAX_VOLUME
    ld [rAUDVOL], a

    ret

; Set the volume to quiet
Quiet::
    ld a, ENABLE_AUDIO
    ld [rAUDENA], a
    ld a, AUDIO_TERM
    ld [rAUDTERM], a

    ld a, QUIET_VOLUME
    ld [rAUDVOL], a
    ret

ENDSECTION 

/*******************************************************
* MUSIC WRAPPERS
********************************************************/

SECTION "MusicFunctions", ROM0

; Play a music track using the fortiSSIMo library
; @param de: music track to play
PlayTrack::
    ld a, d
    ld [wLastTrackPlayed], a
    ld a, e
    ld [wLastTrackPlayed + 1], a

    di
	xor a
	ldh [hUGE_MutedChannels], a
    call hUGE_SelectSong        ; start music

    ld a, 1
    ldh [hIsMusicReady], a
    reti

ReloadTrack::
    ld a, [wLastTrackPlayed]
    ld d, a
    ld a, [wLastTrackPlayed + 1]
    ld e, a

    call PlayTrack
    ret

ENDSECTION

/*******************************************************
* SOUND EFFECTS
********************************************************/

SECTION "SFXFunctions", ROM0

; Make a menu transition SFX
MenuTransitionSound::

    ; -- generated by export-sfx.py --
    ld a, hUGE_CH1_MASK
    ld [hUGE_MutedChannels], a
    ld a, $37
    ld [rNR10], a
    ld a, $80
    ld [rNR11], a
    ld a, $f1
    ld [rNR12], a
    ld a, $ba
    ld [rNR13], a
    ld a, $87
    ld [rNR14], a

    ld a, 10   
    call WaitForFrames

    xor a
    ld [hUGE_MutedChannels], a

    ret

; Make a menu select SFX
MenuSelectSound::

    ; -- generated by export-sfx.py --
    ld a, hUGE_CH1_MASK
    ld [hUGE_MutedChannels], a
    ld a, $8
    ld [rNR10], a
    ld a, $80
    ld [rNR11], a
    ld a, $f1
    ld [rNR12], a
    ld a, $97
    ld [rNR13], a
    ld a, $87
    ld [rNR14], a

    xor a
    ld [hUGE_MutedChannels], a

    ret

; Make a menu offset SFX
MenuOffsetSound::

    ; -- generated by export-sfx.py --
    ld a, $8
    ld [rNR10], a
    ld a, $80
    ld [rNR11], a
    ld a, $f1
    ld [rNR12], a
    ld a, $45
    ld [rNR13], a
    ld a, $87
    ld [rNR14], a

    xor a
    ld [hUGE_MutedChannels], a
    ret
 
ENDSECTION

